# Generated by Django 5.2.3 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_is_cancelled_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('product', 'email'), name='unique_review_per_email_product'),
        ),
    ]
