# Generated by Django 5.2.3 on 2026-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
