# Generated by Django 5.2.3 on 2026-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_homebanner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_banners/'),
        ),
    ]
