# Generated by Django 5.2.3 on 2026-02-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
