# Generated by Django 5.2.3 on 2026-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pos_order',
            field=models.BooleanField(default=False),
        ),
    ]
