# Generated by Django 5.2.3 on 2026-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery'), ('POS', 'POS Billing'), ('cash', 'Cash'), ('upi', 'UPI')], default='razorpay', max_length=20),
        ),
    ]
