# Generated by Django 5.2.3 on 2026-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], help_text='Only for POS Billing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery'), ('pos', 'POS Billing')], default='razorpay', max_length=20),
        ),
    ]
