# Generated by Django 5.2.3 on 2026-03-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_pos_payment_type_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myapp.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.size')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
