# Generated by Django 5.2.3 on 2026-03-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registration'),
        ),
    ]
