# Generated by Django 5.2.3 on 2026-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.BooleanField(default=False),
        ),
    ]
